"""partial unique index on active document sha256

Revision ID: 59a1c4c73b67
Revises: 67f0fcd2cf78
Create Date: 2026-07-12 22:24:55.046890

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59a1c4c73b67"
down_revision: str | Sequence[str] | None = "67f0fcd2cf78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_sha256"), table_name="documents")
    op.create_index(
        "ix_documents_sha256_active",
        "documents",
        ["sha256"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_documents_sha256_active",
        table_name="documents",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_documents_sha256"), "documents", ["sha256"], unique=True)
    # ### end Alembic commands ###
